version: '3.1'
volumes:
  db-data:
services:
  app:
    container_name: think-backend
    image: think-backend:latest
    restart: unless-stopped
    platform: linux/arm64
    build:
      context: .
    ports:
      - "8096:8096"
