spring:
  profiles:
    active: production

---

server:
  port: 9081
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/auth.think.ke/auth.think.ke.keystore
    key-store-password: kangethe
    key-store-type: PKCS12
    key-alias: auth.think.ke

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.think.ke/.well-known/jwks.json
          issuer-uri: https://auth.think.ke/
  config:
    activate:
      on-profile: production
oidc:
  issuer: think.net
  auth_url: https://auth.think.ke/oauth2/authorize
  token_url: https://auth.think.ke/oauth2/token

springdoc:
  swagger-ui:
    oauth:
      client-id: 85d2fc81-5ed0-4276-9101-640026f5eacc
      client-secret: yflW_todW2NtALNqhEhfIyabYLic2Bpcm19o5uDP2IM
fusionauth:
  apikey: ONijuRXlmVe3aUzggTrKCaKl2EC8rJanmru8oZq6Ozw_yp77Y6V0tDPu
  baseurl: https://auth.think.ke/
  tenantId: 0f19389f-dbd1-4853-ab0f-33fcd2ac1ed0
  applicationId: 85d2fc81-5ed0-4276-9101-640026f5eacc

minio:
  #  default-folder: /resources
  #  access-key: mWorR7QeZtLQ4zEL
  access-key: think-access-key
  #  url: http://62.12.115.155:9000
  url: http://52.14.197.167:9000
  bucket: thinking
  #  secret-key: 5uDPnKPMFK2o9e0o1bvi7B0g8X0t5NMF
  secret-key: think-secret-key
#data:
#  mongodb:
#    #      uri: mongodb://testUser:test@62.12.115.155:27017/thinkDB?tls=false
#    uri: mongodb://ian:point90@52.14.197.167:27017/ThinkDB?tls=false?authSource=admin
---
server:
  port: 9080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.think.ke/.well-known/jwks.json
          issuer-uri: https://auth.think.ke/
  config:
    activate:
      on-profile: development
oidc:
  issuer: think.net
  auth_url: https://auth.think.ke/oauth2/authorize
  token_url: https://auth.think.ke/oauth2/token

springdoc:
  swagger-ui:
    oauth:
      client-id: 85d2fc81-5ed0-4276-9101-640026f5eacc
      client-secret: yflW_todW2NtALNqhEhfIyabYLic2Bpcm19o5uDP2IM
fusionauth:
  apikey: ONijuRXlmVe3aUzggTrKCaKl2EC8rJanmru8oZq6Ozw_yp77Y6V0tDPu
  baseurl: https://auth.think.ke/
  tenantId: 0f19389f-dbd1-4853-ab0f-33fcd2ac1ed0
  applicationId: 85d2fc81-5ed0-4276-9101-640026f5eacc
minio:
  #  default-folder: /resources
  #  access-key: mWorR7QeZtLQ4zEL
  access-key: think-access-key
  url: http://52.14.197.167
  bucket: thinking
  secret-key: think-secret-key

app:
  language-url: "https://en.wiktionary.org/wiki/Appendix:ISO_639-3_codes/Africa"