spring:
  profiles:
    active: production

---
server:
  connection-timeout: 540000
  tomcat:
    max-swallow-size: -1
  http:
    port: 9081
  port: 9080
#  ssl:
#    enabled: true
#    key-store: /etc/letsencrypt/live/auth.think.ke/auth.think.ke.keystore.p12
#    key-store-password: kangethe
#    key-store-type: PKCS12
#    key-alias: auth.think.ke

spring:
  config:
    activate:
      on-profile: development
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5GB
      max-request-size: 5GB
  data:
    mongodb:
      #      uri: mongodb://testUser:test@62.12.115.155:27017/thinkDB?tls=false
      #      uri: mongodb://ian:point90@52.14.197.167:27017/ThinkDBTest?tls=false?authSource=
      database: ThinkDBPilot
      authentication-database: admin
      host: 18.218.12.248
      username: ian
      password: point90
      port: 9050
#      connections-per-host: 100
#      min-connections-per-host: 10
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://18.218.12.248:9011/.well-known/jwks.json
          issuer-uri: http://18.218.12.248:9011/

oidc:
  issuer: think.net
  auth_url: http://18.218.12.248:9011/oauth2/authorize
  token_url: http://18.218.12.248:9011/oauth2/token

springdoc:
  swagger-ui:
    oauth:
      client-id: 85d2fc81-5ed0-4276-9101-640026f5eacc
      client-secret: yflW_todW2NtALNqhEhfIyabYLic2Bpcm19o5uDP2IM
fusionauth:
  apikey: 9hmUEht1z98FKCt4F0fareYJI_QdV6-hcB4imnTFvIl1_ovx5hjR9yNM
  baseurl: http://18.218.12.248:9011/
  tenantId: 0f19389f-dbd1-4853-ab0f-33fcd2ac1ed0
  applicationId: 85d2fc81-5ed0-4276-9101-640026f5eacc
minio:
  #  default-folder: /resources
  #  access-key: mWorR7QeZtLQ4zEL
  access-key: think-access-key
  url: http://18.218.12.248:9000
  bucket: thinking
  secret-key: think-secret-key
  port: 9000

app:
  language-url: "https://en.wiktionary.org/wiki/Appendix:ISO_639-3_codes/Africa"
  swahili-url: "https://www.swahilipod101.com/swahili-word-lists/?page="
  bot-url: https://llm.think.ke:5000/chat
---
server:
  connection-timeout: 540000
  tomcat:
    max-swallow-size: -1
  http:
    port: 8080
  port: 9081
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/auth.think.ke/auth.think.ke.keystore.p12
    key-store-password: kangethe
    key-store-type: PKCS12
    key-alias: auth.think.ke
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5GB
      max-request-size: 5GB
  data:
    mongodb:
      #      uri: mongodb://testUser:test@62.12.115.155:27017/thinkDB?tls=false
      #      uri: mongodb://ian:point90@52.14.197.167:27017/ThinkDBTest?tls=false?authSource=
      database: ThinkDBPilot
      authentication-database: admin
      host: 18.218.12.248
      username: ian
      password: point90
      port: 9050
      connections-per-host: 10
      min-connections-per-host: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.think.ke:9013/.well-known/jwks.json
          issuer-uri: https://auth.think.ke:9013/
  config:
    activate:
      on-profile: production
oidc:
  issuer: think.net
  auth_url: https://auth.think.ke:9013/oauth2/authorize
  token_url: https://auth.think.ke:9013/oauth2/token

springdoc:
  swagger-ui:
    oauth:
      client-id: 85d2fc81-5ed0-4276-9101-640026f5eacc
      client-secret: yflW_todW2NtALNqhEhfIyabYLic2Bpcm19o5uDP2IM
fusionauth:
  apikey: 9hmUEht1z98FKCt4F0fareYJI_QdV6-hcB4imnTFvIl1_ovx5hjR9yNM
  baseurl: https://auth.think.ke:9013/
  tenantId: 0f19389f-dbd1-4853-ab0f-33fcd2ac1ed0
  applicationId: 85d2fc81-5ed0-4276-9101-640026f5eacc
minio:
  #  default-folder: /resources
  #  access-key: mWorR7QeZtLQ4zEL
  access-key: think-access-key
  url: http://18.218.12.248:9000
  bucket: thinking
  secret-key: think-secret-key
  port: 9000

app:
  language-url: "https://en.wiktionary.org/wiki/Appendix:ISO_639-3_codes/Africa"
  swahili-url: "https://www.swahilipod101.com/swahili-word-lists/?page="
  bot-url: https://llm.think.ke:5000/chat