spring:
  profiles:
    active: production

---

server:
  port: 9081
#  ssl:
#    enabled: true
#    key-store: /etc/letsencrypt/live/auth.think.ke/auth.think.ke.keystore
#    key-store-password: kangethe
#    key-store-type: PKCS12
#    key-alias: auth.think.ke

spring:
  data:
    mongodb:
      #      uri: mongodb://testUser:test@62.12.115.155:27017/thinkDB?tls=false
#      uri: mongodb://ian:point90@52.14.197.167:27017/ThinkDBProd?tls=false?authSource=
      database: ThinkDB
      authentication-database: admin
      host: 38.242.219.131
      username: kangethe
      password: kangethe
      port: 27017


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://38.242.219.131:9011/.well-known/jwks.json
          issuer-uri: https://38.242.219.131:9011/
  config:
    activate:
      on-profile: production
oidc:
  issuer: acme.com
  auth_url: http://38.242.219.131:9011/oauth2/authorize
  token_url: http://38.242.219.131:9011/oauth2/token

springdoc:
  swagger-ui:
    oauth:
      client-id: 3d85f87c-b550-485e-8ac2-4efd1de9926d
      client-secret: aSX-YnSk7kGLVAIkJlT7drIG-L6ffE5GBHr6GXqP5LI
fusionauth:
  apikey: cq-ehmVXkWn10_Mx2mve3s0MrpE1QZ7M_0Q7vDJsGxunKwzrq7Jpuoy_
  baseurl: http://38.242.219.131:9011/
  tenantId: 495e8d50-e96f-415a-b17f-460885176dbb
  applicationId: 3d85f87c-b550-485e-8ac2-4efd1de9926d

minio:
  #  default-folder: /resources
  #  access-key: mWorR7QeZtLQ4zEL
  access-key: kangethe
  #  url: http://62.12.115.155:9000
  url: http://38.242.219.131:9000
  bucket: thinking
  #  secret-key: 5uDPnKPMFK2o9e0o1bvi7B0g8X0t5NMF
  secret-key: kangethe


app:
  language-url: "https://en.wiktionary.org/wiki/Appendix:ISO_639-3_codes/Africa"
  swahili-url: "https://www.swahilipod101.com/swahili-word-lists/?page="
  bot-url: https://llm.think.ke:5000/chat
---
server:
  port: 9081
spring:
  data:
    mongodb:
      #      uri: mongodb://testUser:test@62.12.115.155:27017/thinkDB?tls=false
      #      uri: mongodb://ian:point90@52.14.197.167:27017/ThinkDBTest?tls=false?authSource=
      database: ThinkDBTest
      authentication-database: admin
      host: 18.218.12.248
      username: ian
      password: point90
      port: 9050
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://3.140.199.14:9011/.well-known/jwks.json
          issuer-uri: http://3.140.199.14:9011/
  config:
    activate:
      on-profile: development
oidc:
  issuer: acme.com
  auth_url: http://3.140.199.14:9011/oauth2/authorize
  token_url: http://3.140.199.14:9011/oauth2/token

springdoc:
  swagger-ui:
    oauth:
      client-id: 3bc70ec3-7013-4d52-a6bf-21694f23be37
      client-secret: H3zd_vO8PZJZgsEPinlwaaiSCVTqvqPnK8_nzlZUpJw
fusionauth:
  apikey: fzUDM7plPkmTjVKKAQB9ssytD6dBqpt-iOEIBXtvNHn_QoqXDYDvZXEe
  baseurl: http://3.140.199.14:9011/
  tenantId: d6d1a6e2-2c5d-4317-80fd-05239202af17
  applicationId: 3bc70ec3-7013-4d52-a6bf-21694f23be37
minio:
  #  default-folder: /resources
  #  access-key: mWorR7QeZtLQ4zEL
  access-key: thinking
  url: http://3.140.199.14
  bucket: thinking
  secret-key: thinking

app:
  language-url: "https://en.wiktionary.org/wiki/Appendix:ISO_639-3_codes/Africa"
  swahili-url: "https://www.swahilipod101.com/swahili-word-lists/?page="
  bot-url: https://llm.think.ke:5000/chat