server:
  port: 9080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://52.14.197.167:9011/.well-known/jwks.json
          issuer-uri: http://52.14.197.167:9011/
oidc:
  issuer: think.net
  auth_url: http://52.14.197.167:9011/oauth2/authorize
  token_url: http://52.14.197.167:9011/oauth2/token

springdoc:
  swagger-ui:
    oauth:
      client-id: 85d2fc81-5ed0-4276-9101-640026f5eacc
      client-secret: yflW_todW2NtALNqhEhfIyabYLic2Bpcm19o5uDP2IM