name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ikangethe/think-fusion-auth:latest
  deploy_to_think-server:
    runs-on: ubuntu-latest
    needs: build_and_push
    name: Deploy to Think Server
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker stop think-auth-fusion-container1
            docker rm think-auth-fusion-container1
            docker pull ikangethe/think-fusion-auth:latest
            docker run -d -p "9081:9081" -p "8080:8080" --restart=unless-stopped --name=think-auth-fusion-container1 ikangethe/think-fusion-auth:latest
            docker ps -a

  deploy_to_think-server-admin:
    runs-on: ubuntu-latest
    needs: build_and_push
    name: Deploy to Think Server for Admin
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTADMIN }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker stop think-auth-fusion-container1
            docker rm think-auth-fusion-container1
            docker pull ikangethe/think-fusion-auth:latest
            docker run -d -p "9081:9081" -p "8080:8080" --restart=unless-stopped --name=think-auth-fusion-container1 ikangethe/think-fusion-auth:latest
            docker ps -a